default_stages: [commit]
exclude: ^(old_code|cicd)/.*

repos:
  # standard built in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Removes trailing whitespaces
        exclude: \.txt$
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
        exclude: \.txt$
      - id: check-yaml # Loads all yaml files to verify syntax
        exclude: \.txt$
      - id: check-added-large-files # Prevents giant files from being committed (default=500kB)
        exclude: \.txt$
      - id: debug-statements # Removes debug statements which should never be in production
        exclude: \.txt$
      - id: requirements-txt-fixer # Sorts entries in requirements.txt and constraints.txt and removes incorrect entry for pkg-resources==0.0.0
        exclude: \.txt$

  # Python code formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # # Run the formatter.
      # - id: ruff-format
      #   types_or: [ python, pyi, jupyter ]

  # Sort your imports automatically
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["-l", "120", "--profile", "black"]

  # autoflake removes unused import statements, config in args below
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']

  # Toolkit for checking your code base against coding style (PEP8), programming errors and check cyclomatic complexity
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]

 # To enforce type hinting
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports  # Ignore missing imports: useful for third-party libraries and inter-module imports
          - --disable-error-code  # Disable the error code, which is useful for ignoring specific errors
          - no-any-unimported  # Disables the error code no-any-unimported
          - --explicit-package-bases  # Explicit package bases: useful for avoiding ambiguous type errors
        exclude: ^((tests)|(tooling)|(docs)|(notebooks)|(^.*notebook.py))$
        additional_dependencies:
          - "types-PyYAML"

  # Notebook remove results
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["-l", "120"]
        additional_dependencies:
          - "click==8.1.3" # Required in order for black to run

  # Run black on python code blocks in documentation files
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - "black==22.1"

  # SQL linter that supports many dialects
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.13.2
    hooks:
      - id: sqlfluff-lint

  # Format YAML files
  # - repo: https://github.com/google/yamlfmt
  #   rev: v0.14.0
  #   hooks:
  #     - id: yamlfmt

  # validate Markdown / RST files
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter

  # Syntax update for newer Python versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
